# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './options.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.resize(583, 359)
        self.verticalLayout = QtWidgets.QVBoxLayout(OptionsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(OptionsDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.appearanceTab = QtWidgets.QWidget()
        self.appearanceTab.setObjectName("appearanceTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.appearanceTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.darkModeCheckBox = QtWidgets.QCheckBox(self.appearanceTab)
        self.darkModeCheckBox.setChecked(False)
        self.darkModeCheckBox.setObjectName("darkModeCheckBox")
        self.verticalLayout_5.addWidget(self.darkModeCheckBox)
        self.checkBox = QtWidgets.QCheckBox(self.appearanceTab)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_5.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.tabWidget.addTab(self.appearanceTab, "")
        self.protocolOptionTab = QtWidgets.QWidget()
        self.protocolOptionTab.setObjectName("protocolOptionTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.protocolOptionTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.showBluetoothNames = QtWidgets.QCheckBox(self.protocolOptionTab)
        self.showBluetoothNames.setChecked(True)
        self.showBluetoothNames.setObjectName("showBluetoothNames")
        self.verticalLayout_2.addWidget(self.showBluetoothNames)
        self.showBluetoothServices = QtWidgets.QCheckBox(self.protocolOptionTab)
        self.showBluetoothServices.setObjectName("showBluetoothServices")
        self.verticalLayout_2.addWidget(self.showBluetoothServices)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.protocolOptionTab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.bluetoothRefreshRate = QtWidgets.QSpinBox(self.protocolOptionTab)
        self.bluetoothRefreshRate.setMinimum(1)
        self.bluetoothRefreshRate.setMaximum(60)
        self.bluetoothRefreshRate.setSingleStep(1)
        self.bluetoothRefreshRate.setProperty("value", 1)
        self.bluetoothRefreshRate.setObjectName("bluetoothRefreshRate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bluetoothRefreshRate)
        self.label_7 = QtWidgets.QLabel(self.protocolOptionTab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.wifiRefreshRate = QtWidgets.QSpinBox(self.protocolOptionTab)
        self.wifiRefreshRate.setMinimum(1)
        self.wifiRefreshRate.setMaximum(60)
        self.wifiRefreshRate.setSingleStep(1)
        self.wifiRefreshRate.setProperty("value", 1)
        self.wifiRefreshRate.setObjectName("wifiRefreshRate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.wifiRefreshRate)
        self.wifiSwitch = QtWidgets.QCheckBox(self.protocolOptionTab)
        self.wifiSwitch.setEnabled(True)
        self.wifiSwitch.setChecked(False)
        self.wifiSwitch.setObjectName("wifiSwitch")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.wifiSwitch)
        self.bluetoothSwitch = QtWidgets.QCheckBox(self.protocolOptionTab)
        self.bluetoothSwitch.setChecked(False)
        self.bluetoothSwitch.setObjectName("bluetoothSwitch")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.bluetoothSwitch)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.tabWidget.addTab(self.protocolOptionTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(OptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OptionsDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(OptionsDialog.accept)
        self.buttonBox.rejected.connect(OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialog.setWindowTitle(_translate("OptionsDialog", "Preferences"))
        self.darkModeCheckBox.setText(_translate("OptionsDialog", "Dark Mode"))
        self.checkBox.setText(_translate("OptionsDialog", "Display Consolidated Graphs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appearanceTab), _translate("OptionsDialog", "Appearance"))
        self.showBluetoothNames.setText(_translate("OptionsDialog", "Show bluetooth names (updates will be slower)"))
        self.showBluetoothServices.setText(_translate("OptionsDialog", "Show bluetooth services (updates willl be slower)"))
        self.label_2.setText(_translate("OptionsDialog", "Bluetooth Device Refresh rate (sec)"))
        self.label_7.setText(_translate("OptionsDialog", "WiFi Device Refresh rate (sec)"))
        self.wifiSwitch.setText(_translate("OptionsDialog", "Turn Wifi on"))
        self.bluetoothSwitch.setText(_translate("OptionsDialog", "Turn Bluetooth on"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.protocolOptionTab), _translate("OptionsDialog", "Protocols"))


